# action.yml

name: git-trailers
description: "Action that adds Reviewed-by/Approved-by and PR trailers in git commits of a PR"

inputs:
  user_info: 
    description: "Filepath to .yaml file with user info (github username, name, email)"
    required: false


runs:
    using: 'composite'
    steps:
#    - name: Debug github events
#      id: tmp
#      shell: bash
#      run: |
#        echo "github.head_ref:" ${{ github.head_ref}}
#        echo "github.ref:" ${{ github.ref }}
#        echo "github.ref_name:" ${{ github.ref_name }}
#        echo "github.event.number:" ${{ github.event.number }}
#        echo "github.event.pull_request.base.ref:" ${{ github.event.pull_request.base.ref }}
#        echo "github.event.pull_request.head.ref:" ${{ github.event.pull_request.head.ref }}
#        echo "github.event.pull_request.number:" ${{ github.event.pull_request.number }}

    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1.1.1
      with:
        version: v4.40.5

    - name: Parse inputs
      shell: bash
      run: |
        if [ -n "${{ inputs.user_info }}" ]; then
          USER_INFO=$(cat "${{ inputs.user_info }}" | base64 -w 0)
        else
          USER_INFO=$(cat "${{ github.action_path }}"/resources/users_info.yml | base64 -w 0)
        fi
        echo "user_info=$USER_INFO" >> $GITHUB_ENV

    - name: Get repo branches
      shell: bash
      run: |
        repo_branches=$(curl --location 'https://api.github.com/repos/${{ github.repository }}/branches' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ github.token }}' \
        --header 'X-GitHub-Api-Version: 2022-11-28')
        echo "repo_branches: $(echo $repo_branches)"
        echo "target_branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
        echo "target_branch: ${{ github.event.pull_request.base.ref }}"

    - name: Get PR info
      shell: bash
      run: |
         pr_info=$(curl --location 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}' \
         --header 'Accept: application/vnd.github+json' \
         --header 'Authorization: Bearer ${{ github.token }}' \
         --header 'X-GitHub-Api-Version: 2022-11-28')
         pr_user=$(echo $pr_info | jq -e .user.login | sed 's/\[//g' | sed 's/\]//g' | sed 's/\,//g' | sed 's/\"//g')
         echo "pr_user=$pr_user" >> $GITHUB_ENV
         echo "pull request user: " $pr_user

         pr_commits_full=$(curl --location 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
         --header 'Accept: application/vnd.github+json' \
         --header 'Authorization: Bearer ${{ github.token }}' \
         --header 'X-GitHub-Api-Version: 2022-11-28')
         pr_commits=$(echo $pr_commits_full | jq -re '.[].sha')
         {
         echo 'PR_COMMITS_GHENV<<EOF'
         echo $pr_commits
         echo EOF
         } >> "$GITHUB_ENV"
         echo $PR_COMMITS_GHENV

         pr_reviews=$(curl --location 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=300' \
         --header 'Accept: application/vnd.github+json' \
         --header 'Authorization: Bearer ${{ github.token }}' \
         --header 'X-GitHub-Api-Version: 2022-11-28')
         pr_reviewers=$(echo $pr_reviews | jq 'map(.user.login) | unique' | sed 's/\[//g' | sed 's/\]//g' | sed 's/\,//g' | sed 's/\"//g')
         echo "pull reviewers: " $pr_reviewers
         {
         echo 'PR_REVIEWERS_GHENV<<EOF'
         echo $pr_reviewers
         echo EOF
         } >> "$GITHUB_ENV"
         echo $PR_REVIEWERS_GHENV
         pr_approver=$(echo $pr_reviews | jq  -rce 'map(select(.state == "APPROVED"))' | jq 'map(.user.login) | unique' |sed 's/\[//g' | sed 's/\]//g' | sed 's/\,//g' | sed 's/\"//g')
         echo "pull request approver: " $pr_approver
         {
         echo 'PR_APPROVER_GHENV<<EOF'
         echo $pr_approver
         echo EOF
         } >> "$GITHUB_ENV"
         echo $PR_APPROVER_GHENV

    - name: Generate REVIEWER trailer strings
      shell: bash
      run: |
        trailers=()
        for i in $(echo $PR_REVIEWERS_GHENV); do \
          if [[ "$i" == "$pr_user" ]]; then
            continue
          fi
          # skip github actionsbot as a reviewer
          if [[ "$i" == "github-actionsbot" ]]; then
            continue
          fi
          echo "Author was $pr_user"
          echo "reviewers item: $i"
          gh_user=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i - )
          echo "user: $gh_user"
          if ! [[ $gh_user == "null" ]]; then
            gh_user_name=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i.name - )
            gh_user_email=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i.email - )
            trailers+=("review: $gh_user_name <$gh_user_email>")
          else
            echo "user not found in users info resource file... exiting... "
            exit 1
          fi
        done
        trailers_json=$(jq -c -n '$ARGS.positional' --args "${trailers[@]}")
        echo "reviewer_trailers=$trailers_json" >> $GITHUB_ENV
        echo "reviewer_trailers=$trailers_json"


    - name: Generate APPROVER trailer strings
      shell: bash
      run: |
        trailers=()
        for i in `echo $PR_APPROVER_GHENV`; do \
          echo "approver item: " $i
          gh_user=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i - )
          if ! [[ $gh_user == "null" ]]; then
            gh_user_name=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i.name - )
            gh_user_email=$(echo ${{ env.user_info }} | base64 -d | yq .users.$i.email - )
            trailers+=("approve: $gh_user_name <$gh_user_email>")
          else
            echo "user not found in users info resource file... exiting... "
            exit 1
          fi
        done
        trailers_json=$(jq -c -n '$ARGS.positional' --args "${trailers[@]}")
        echo "approver_trailers=$trailers_json" >> $GITHUB_ENV
        echo "approver_trailers=$trailers_json"

    - name: Update remote branch with trailer info
      shell: bash
      run: |
        echo "Preparing git environment"
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}
        git clean -fd
        git status
        git config trailer.sign.key "Signed-off-by"
        git config trailer.review.key "Reviewed-by"
        git config trailer.approve.key "Approved-by"
        git config trailer.pr.key "PR"
        git config trailer.pr.where "start"
        echo "Setting up user"
        gh_user=$(echo ${{ env.user_info }} | base64 -d | yq .users.$pr_user - )
        echo "user: $gh_user"
        if ! [[ $gh_user == "null" ]]; then
          gh_user_name=$(echo ${{ env.user_info }} | base64 -d | yq .users.$pr_user.name - )
          gh_user_email=$(echo ${{ env.user_info }} | base64 -d | yq .users.$pr_user.email - )
        else
          echo "user not found in users info resource file... exiting... "
          exit 1
        fi       
        git config user.email $gh_user_email
        git config user.name $gh_user_name
        pr_trailer="[\"pr: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}\"]"
        trailer_args="--trailer \"pr: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}\""
        trailers_json=$(echo -e "$reviewer_trailers\n$approver_trailers" | jq -s 'add')
        trailers=$(echo "$trailers_json" | jq -c -r '.[]')
        IFS=$'\n'
        for i in $trailers; do
          [ -n "$i" ] && trailer_args+=" --trailer \"$i\""
        done;
        unset IFS
        echo "Adding trailers"
        git rebase origin/${{ env.target_branch }} \
          -x "git commit --amend --allow-empty --no-edit $trailer_args"
        echo "Pushing to origin/branch" ${{ github.event.pull_request.head.ref }}
        git push -f origin ${{ github.event.pull_request.head.ref }}

